### PR TITLE
Add flags and change String to &'static str

### PR DESCRIPTION
**Pull request by farodin91**

### CODE REVIEW

**Comment by farodin91** [comment]
@jimmycuadra I'll try to implement the server component in new PR.
This ready to review.

**Comment by jimmycuadra** [comment]
I'm not sure I understand the motivation for the `to_string` function. The result seems to be the same as the previous `request_path` implementation, but the implementation is much more complicated.

The flags idea seems good, although we could also just have two methods like `requires_authentication` and `rate_limited` that return booleans.

Was the `Send + Sync` constraint on `Endpoint` needed to satisfy Iron somehow?

**Comment by farodin91** [comment]
I implemented to_string to prevent doing two times in `router_path` and `request_path`.

I like the idea of vectors, because you don't have to change all api's. If matrix add a new flag.

Send + Sync was for Iron. I will remove this for now.

**Comment by jimmycuadra** [comment]
There would still be a breaking change for new flags because a new variant would be added to the enum. At the site of use, being able to call a function with a boolean result would be more expressive than checking for the presence of a particular value in a vector, too.

**Comment by vberger** [comment]
Regarding the flags, wouldn't it be a typical use-case for [bitflags](https://crates.io/crates/bitflags)?

**Comment by farodin91** [comment]
@jimmycuadra I like the idea of @vberger. What do you think?

**Comment by jimmycuadra** [comment]
What's the advantage of bitflags if you're not interoperating with C code?

**Comment by vberger** [comment]
Mostly: It's more space efficient and you can easily check for multiple flags at once (might be relevant if in the future more flags are added, and you need to check for the combination of 3 or 4 flags ?).

On a much more subjective argument, imo it feels like the right way to represent this information (I don't expect to convince you this that ^^ but that's why I suggested it).

**Comment by jimmycuadra** [comment]
Gotcha. I still think separate predicate functions for each one is the best choice. There happen to be two "flags" now, but I don't think we can assume that this is future-compatible when we have absolutely no idea how the spec might change in the future. Differences in space efficiency are trivial for such a small thing, so I don't think that is really a consideration in determining an interface for this information.

We have to go by the information we have now:

Some endpoints require authentication. Some endpoints are rate limited. These two things have nothing to do with each other. They both happen to be representable by booleans that answer the question "does this endpoint have this property"?

Based on that, I don't think it makes sense to group the two properties together in any way.

**Comment by vberger** [comment]
I see your point, sounds totally reasonable indeed.

**Comment by farodin91** [comment]
I changed the api by adding two default functions with value `false`. 

@jimmycuadra This should be complete for now.

**Comment by jimmycuadra** [comment]
Sorry—a few more thoughts:

* What is the motivation for `PathParams` and `QueryParams` being `Deserialize + Serialize`? For converting `PathParams` to a string path (ruma-client), we have the `request_path` method. For converting a router path to `PathParams` (ruma), we have our various `XParam` middleware. We might come up with something easier than that later. For `QueryParams`, on the client side, I don't see serialization as being particularly useful. More likely we'd want some sort of functionality in ruma-client for adding the fields of the struct to the query string of component of a `Url`. And again, on the server side, we have middleware.
* I think the return type of `name` and `description` can be `&'static str`. Can we get away with that or can anyone think of a reason it needs to be `String`? And further: can we get away with removing the `description` method entirely? Are docstrings on the implementing type sufficient? Or is there a case where the description needs to be accessed programmatically?
* I'd rather err on the side of caution and not provide default implementations for `requires_authentication` and `rate_limited`. Default implementations seem more appropriate for getting rid of boilerplate or obvious logic, but in this case I think we want to make sure that each implementation of `Endpoint` explicitly declares its intent.

**Comment by farodin91** [comment]
- I add `description` to support auto generated swagger, but not anytime soon possibly.
- The spec only define with one them is true. Removing the default implementation is no problem for me.
- Removing `Serialize` from `PathParams`, no problem.
- Adding `Deserialize` to `PathParams` and `QueryParams` reduces boilerplate work. We don't have to add multiple middlewares. 
- For QueryParams, we don't have a great middleware. With `Deserialize`, it would be easy to build one. `rust-url`support deserialize of query params, with `serde_urlencoded`.

**Comment by jimmycuadra** [comment]
Good idea on the description for Swagger. We'll keep it.

Let's go ahead and remove the default implementations of the methods.

I guess I'm not seeing how `PathParams` and `QueryParams` could be easily deserialized on the server side just by having them implement `Deserialize`. rust-url only implements the Serde traits for `Url`. It seems only intended for converting between strings and the `Url` type.

**Comment by farodin91** [comment]
You need also `serde_urlencoded`.

**Comment by jimmycuadra** [comment]
Ah, I thought you were saying `serde_urlencoded` was a Cargo feature of `rust-url`.

**Comment by farodin91** [comment]
Sorry, My vault. My english isn't so good.

**Comment by farodin91** [comment]
@jimmycuadra What i have to do next at this PR?

**Comment by jimmycuadra** [comment]
As you probably saw, I just pushed and released a change that add `Deserialize` and `Serialize` constraints to just `Endpoint::QueryParams`. I did this for ruma-client, using serde_urlencoded, as you suggested. You'll want to rebase your branch and remove the redundant addition there.

I'm still not sure about `Endpoint::PathParams` needing de/serialization. Just calling `Endpoint::request_path(path_params)` works fine for creating a `Url` for requests in ruma-client, so I don't think there is a need for serialization. I haven't thought more about how deserialization might be used.

All the new methods signatures are good, but we can improve the docstrings a bit:

* name: A unique identifier for this endpoint, suitable for \`Router\` from the router crate.
* description: A human-readable description of the endpoint.
* requires_authentication: Whether or not this endpoint requires an authenticated user.
* rate_limited: Whether or not this endpoint is rate limited.

**Pull request merged**
